version: '3.8'

services:
  app:
    image: 'docker-spring-boot-postgres:latest'
    ports:
      - "8080:8080"
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/mpp
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - WAIT_HOSTS=postgres:5432
      - WAIT_TIMEOUT=10000000
      - WAIT_SLEEP_INTERVAL=5
    networks:
      - app-network

  db:
    image: 'postgres:15.2-alpine'
    hostname: postgres
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mpp
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
